// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8DcP-8l9TP7J9vRO4ItmEX7pC5H85V5w',
    appId: '1:1061541553259:web:660aedfc927e72d7a47d2e',
    messagingSenderId: '1061541553259',
    projectId: 'movie-app-834a4',
    authDomain: 'movie-app-834a4.firebaseapp.com',
    storageBucket: 'movie-app-834a4.appspot.com',
    measurementId: 'G-HXZ8Q6XW9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5B5oocLNM6IUNfZEyf2mf27Oj8V7NE-s',
    appId: '1:1061541553259:android:7c2a148425f89213a47d2e',
    messagingSenderId: '1061541553259',
    projectId: 'movie-app-834a4',
    storageBucket: 'movie-app-834a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLMqcP5QJ205wT2lgHLDRQHxRVcdXvH58',
    appId: '1:1061541553259:ios:df7cae8407e6f8b8a47d2e',
    messagingSenderId: '1061541553259',
    projectId: 'movie-app-834a4',
    storageBucket: 'movie-app-834a4.appspot.com',
    iosClientId: '1061541553259-gd7kjss9r6922lqj4s5lj8mgv0v7607b.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
